// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          int64
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DueDate     sql.NullTime
	Priority    sql.NullInt64
	Tags        sql.NullString
	ParentID    sql.NullInt64
	CompletedAt sql.NullTime
	Progress    sql.NullInt64
	Archived    bool
	Status      string
}
